"""Styled widget layout for the shared showcase; source logic lives elsewhere."""
# Copyright (c) 2025, 2026 Hans De Weme
# Licensed under the MIT License (https://opensource.org/licenses/MIT).
# part of the HdW_crypto_data Project
#
#PyQt imports
from PyQt6.QtCore import Qt, QSize
from PyQt6.QtWidgets import (
    QWidget, QVBoxLayout, QHBoxLayout, QLabel, QComboBox, QLineEdit,
    QPushButton, QSpinBox, QCheckBox, QTextEdit, QGroupBox, QSplitter,
    QListWidget, QListView, QAbstractItemView, QProgressBar, QTableWidget,
    QHeaderView,
)


def build_ui(window):
    central = QWidget()
    window.setCentralWidget(central)
    main = QHBoxLayout(central)
    main.setContentsMargins(14, 14, 14, 14)
    splitter = QSplitter(Qt.Orientation.Horizontal)
    main.addWidget(splitter)

    left = QWidget()
    left.setMinimumWidth(360)
    left_layout = QVBoxLayout(left)
    left_layout.setContentsMargins(0, 0, 0, 0)
    window.asset_group = QGroupBox('Select assets')
    assets = QVBoxLayout(window.asset_group)
    window.source_combo = QComboBox()
    window.source_combo.addItems(['Yahoo stocks', 'Binance crypto'])
    assets.addWidget(window.source_combo)
    window.search_bar = QLineEdit()
    window.search_bar.setPlaceholderText('Search assets...')
    window.search_bar.textChanged.connect(window.filter_assets)
    assets.addWidget(window.search_bar)
    window.asset_list = QListWidget()
    window.asset_list.setObjectName('assetList')
    window.asset_list.setIconSize(QSize(24, 24))
    window.asset_list.setWrapping(True)
    window.asset_list.setFlow(QListView.Flow.LeftToRight)
    window.asset_list.setResizeMode(QListView.ResizeMode.Adjust)
    window.asset_list.setMovement(QListView.Movement.Static)
    window.asset_list.setGridSize(QSize(158, 42))
    window.asset_list.setUniformItemSizes(True)
    window.asset_list.setSelectionMode(QAbstractItemView.SelectionMode.ExtendedSelection)
    window.asset_list.itemChanged.connect(window.update_selection_counter)
    window.asset_list.itemSelectionChanged.connect(window.update_selection_counter)
    assets.addWidget(window.asset_list, 1)
    custom = QHBoxLayout()
    window.symbol_input = QLineEdit()
    window.symbol_input.setPlaceholderText('Add symbols, e.g. AAPL, ^GSPC')
    window.add_custom_btn = QPushButton('+ Add')
    window.add_custom_btn.clicked.connect(window.add_custom_assets)
    window.symbol_input.returnPressed.connect(window.add_custom_assets)
    custom.addWidget(window.symbol_input, 1)
    custom.addWidget(window.add_custom_btn)
    assets.addLayout(custom)
    helpers = QHBoxLayout()
    window.select_all_btn = QPushButton('Select visible')
    window.select_all_btn.clicked.connect(lambda: window.set_all_checked(True))
    window.clear_selection_btn = QPushButton('Clear')
    window.clear_selection_btn.clicked.connect(lambda: window.set_all_checked(False))
    helpers.addWidget(window.select_all_btn)
    helpers.addWidget(window.clear_selection_btn)
    assets.addLayout(helpers)
    window.selection_label = QLabel('0 assets selected')
    assets.addWidget(window.selection_label)
    window.icon_path_label = QLabel()
    window.icon_path_label.setWordWrap(True)
    window.icon_path_label.setObjectName('mutedLabel')
    assets.addWidget(window.icon_path_label)
    left_layout.addWidget(window.asset_group)
    splitter.addWidget(left)

    right = QWidget()
    layout = QVBoxLayout(right)
    layout.setContentsMargins(0, 0, 0, 0)
    layout.setSpacing(10)
    window.dependency_notice = QLabel()
    window.dependency_notice.setWordWrap(True)
    window.dependency_notice.setTextFormat(Qt.TextFormat.PlainText)
    window.dependency_notice.setTextInteractionFlags(Qt.TextInteractionFlag.TextSelectableByMouse)
    window.dependency_notice.setStyleSheet('color: #f6e05e;')
    layout.addWidget(window.dependency_notice)
    window.pipeline_group = QGroupBox('Creation pipeline')
    options = QVBoxLayout(window.pipeline_group)
    options_row = QHBoxLayout()
    options_row.addWidget(QLabel('Interval: 1h'))
    window.days_label = QLabel('Lookback')
    options_row.addWidget(window.days_label)
    window.days_spin = QSpinBox()
    window.days_spin.setRange(1, 730)
    window.days_spin.setValue(730)
    window.days_spin.setSuffix(' days')
    options_row.addWidget(window.days_spin)
    options_row.addWidget(QLabel('Timezone'))
    window.timezone_input = QLineEdit(window.settings['preferred_time_zone'])
    options_row.addWidget(window.timezone_input, 1)
    options.addLayout(options_row)
    window.archive_check = QCheckBox('1. Download / update Binance historical archives')
    window.archive_check.setChecked(True)
    options.addWidget(window.archive_check)
    window.force_check = QCheckBox('Allow building the total dataset with historical gaps')
    options.addWidget(window.force_check)
    window.pipeline_description = QLabel()
    window.pipeline_description.setWordWrap(True)
    options.addWidget(window.pipeline_description)
    layout.addWidget(window.pipeline_group)
    actions = QHBoxLayout()
    window.load_button = QPushButton('Start batch processing')
    window.load_button.setObjectName('startBtn')
    window.load_button.clicked.connect(window.start_processing)
    window.stop_button = QPushButton('Stop')
    window.stop_button.setObjectName('stopBtn')
    window.stop_button.setToolTip('Stop after the current asset finishes')
    window.stop_button.setEnabled(False)
    window.stop_button.clicked.connect(window.stop_processing)
    window.csv_button = QPushButton('Open CSV')
    window.csv_button.clicked.connect(window.open_csv)
    actions.addWidget(window.load_button, 3)
    actions.addWidget(window.stop_button, 1)
    actions.addWidget(window.csv_button, 1)
    layout.addLayout(actions)
    window.progress_bar = QProgressBar()
    window.progress_bar.setRange(0, 1)
    window.progress_bar.setValue(0)
    window.progress_bar.setFormat('Ready')
    layout.addWidget(window.progress_bar)
    window.table = QTableWidget(0, 5)
    window.table.setHorizontalHeaderLabels(['Asset', 'Source', 'Pipeline', 'Rows', 'Details'])
    window.table.setEditTriggers(QAbstractItemView.EditTrigger.NoEditTriggers)
    window.table.setSelectionBehavior(QAbstractItemView.SelectionBehavior.SelectRows)
    for column in range(4):
        window.table.horizontalHeader().setSectionResizeMode(column, QHeaderView.ResizeMode.ResizeToContents)
    window.table.horizontalHeader().setSectionResizeMode(4, QHeaderView.ResizeMode.Stretch)
    window.table.setMinimumHeight(135)
    window.table.setMaximumHeight(200)
    layout.addWidget(window.table)

    charts = QGroupBox('Shared charting and technical analysis')
    chart_layout = QVBoxLayout(charts)
    asset_row = QHBoxLayout()
    asset_row.addWidget(QLabel('Dataset'))
    window.chart_asset_combo = QComboBox()
    window.chart_asset_combo.setMinimumContentsLength(20)
    window.chart_asset_combo.setSizeAdjustPolicy(QComboBox.SizeAdjustPolicy.AdjustToMinimumContentsLengthWithIcon)
    asset_row.addWidget(window.chart_asset_combo, 1)
    chart_layout.addLayout(asset_row)
    chart_row = QHBoxLayout()
    window.chart_type_combo = QComboBox()
    for label, key, period, unit in (
        ('Candlesticks / RSI / Stochastic', 'raw', 30, 'days'),
        ('Price / Volume / Trades', 'pricevol', 96, 'hours'),
        ('Keltner channels', 'keltner', 32, 'days'),
        ('Moving averages', 'sma', 30, 'days'),
        ('Bollinger / RSI / STC', 'sim', 32, 'days'),
        ('Gaussian bands', 'gauss', 30, 'days'),
    ):
        window.chart_type_combo.addItem(label, (key, period, unit))
    window.chart_period_spin = QSpinBox()
    window.chart_period_spin.setRange(1, 100000)
    window.chart_type_combo.currentIndexChanged.connect(window.update_chart_period_control)
    window.update_chart_period_control()
    window.show_chart_btn = QPushButton('Show chart')
    window.show_chart_btn.clicked.connect(window.show_selected_chart)
    window.save_chart_df_btn = QPushButton('Save enhanced CSV')
    window.save_chart_df_btn.clicked.connect(window.save_selected_chart_dataframe)
    for widget in (window.chart_asset_combo, window.chart_type_combo, window.chart_period_spin,
                   window.show_chart_btn, window.save_chart_df_btn):
        widget.setEnabled(False)
    chart_row.addWidget(window.chart_type_combo, 1)
    for widget in (window.chart_period_spin, window.show_chart_btn, window.save_chart_df_btn):
        chart_row.addWidget(widget)
    chart_layout.addLayout(chart_row)
    window.metadata_label = QLabel('Complete a pipeline or open a CSV to start charting.')
    window.metadata_label.setWordWrap(True)
    chart_layout.addWidget(window.metadata_label)
    layout.addWidget(charts)
    log_header = QHBoxLayout()
    log_header.addWidget(QLabel('Live execution console'), 1)
    clear_log = QPushButton('Clear console')
    clear_log.clicked.connect(lambda: window.log_console.clear())
    log_header.addWidget(clear_log)
    layout.addLayout(log_header)
    window.log_console = QTextEdit()
    window.log_console.setObjectName('logConsole')
    window.log_console.setReadOnly(True)
    window.log_console.setMinimumHeight(90)
    layout.addWidget(window.log_console, 1)
    splitter.addWidget(right)
    splitter.setStretchFactor(0, 0)
    splitter.setStretchFactor(1, 1)
    splitter.setSizes([380, 840])
    window.source_combo.currentIndexChanged.connect(window.source_changed)
    window.chart_asset_combo.currentIndexChanged.connect(window.update_metadata)
