[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"

[project]
name = "HdWCryptoData"  #  Name for PyPI
dynamic = ["version"]
authors = [
    { name="Hans De Weme", email="hdweme@gmail.com" }
]
description = "retrieve and normalized and optionally chart crypto data from Binance Vision and Binance Rest API"
readme = "readme.md"
requires-python = ">=3.11"
license = "MIT"
dependencies = [
    "certifi",
    "numpy",
    "pandas",
    "python-dateutil",
    "requests",
    "tqdm",
    "urllib3",
]

[project.optional-dependencies]
parallel = ["mpire"]
analysis = [
    "openpyxl",
    "pandas-ta",
    "plotly",
    "progressbar2",
    "scipy",
    "ta",
]
gui = [
    "hdw-crypto-data[analysis]",
    "PyQt6",
]

[tool.setuptools.dynamic]
version = {attr = "hdw_crypto_data.version.VERSION"}

[tool.setuptools.packages.find]
include = ["hdw_crypto_data*"]

classifiers = [
    "Programming Language :: Python :: 3",
    "License :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/hansdeweme/HdWCryptoData.git"